# Generated by Django 4.0.6 on 2022-08-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('date', models.DateField(auto_now=True)),
                ('cookingimages_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('cookingimages_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('cookingimages_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('ingredients', models.TextField()),
                ('recepi', models.TextField()),
                ('memo', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
