# Generated by Django 4.0.6 on 2022-08-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookrecord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordmodel',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
