# Generated by Django 4.0.6 on 2022-08-06 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookrecord', '0003_recordmodel_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordmodel',
            name='cookingimages_1',
            field=models.ImageField(blank=True, null=True, upload_to='cook_pics'),
        ),
        migrations.AlterField(
            model_name='recordmodel',
            name='cookingimages_2',
            field=models.ImageField(blank=True, null=True, upload_to='cook_pics'),
        ),
        migrations.AlterField(
            model_name='recordmodel',
            name='cookingimages_3',
            field=models.ImageField(blank=True, null=True, upload_to='cook_pics'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('account_image', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
